# Change these first
owner: MailCheck-co # Your GitHub organization or username
repo: status # Your GitHub repository name

# Add your sites here
sites:
  - name: landing
    url: https://www.mailcheck.co
  - name: cabinet
    url: https://app.mailcheck.co
  - name: API singleEmail
    url: https://api.mailcheck.co/v1/singleEmail:check
    headers:
      - "Authorization: Bearer $APIKEY"
      - "Content-Type: application/json"
    body: '{ "email": "nosov@nodeart.io" }'

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.mailcheck.co
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/MailCheck-co/mailcheck.site/master/static/assets/img/mailcheck-logo.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: Current ststus of Mailcheck.co services
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
