# Change these first
owner: MailCheck-co # Your GitHub organization or username
repo: status # Your GitHub repository name

# Add your sites here
sites:
  - name: landing
    url: https://www.mailcheck.co
  - name: landing 404 test
    url: https://www.mailcheck.co/404
    expectedStatusCodes:
      - 404
  - name: cabinet
    url: https://app.mailcheck.co
    icon: https://www.mailcheck.co/favicon.png
  - name: cabinet 404 test
    url: https://app.mailcheck.co/404
    icon: https://www.mailcheck.co/favicon.png
    expectedStatusCodes:
      - 404
  - name: API singleEmail
    url: https://api.mailcheck.co/v1/singleEmail:check
    method: POST
    headers:
      - "Authorization: Bearer $APIKEY"
      - "Content-Type: application/json"
    body: '{ "email": "nosov@nodeart.io" }'
    maxResponseTime: 20000
    icon: https://www.mailcheck.co/favicon.png
  - name: API singleEmail wrong method
    url: https://api.mailcheck.co/v1/singleEmail:check
    method: GET
    expectedStatusCodes:
      - 404
    maxResponseTime: 5000
    icon: https://www.mailcheck.co/favicon.png

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.mailcheck.co
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  theme: dark
  logoUrl: https://raw.githubusercontent.com/MailCheck-co/mailcheck.site/master/static/assets/img/mailcheck-logo.svg
  name: Upptime
  introTitle: "**Mailcheck** Email validations and contact enrichment service."
  introMessage: "Current ststus of [Mailcheck.co](https://www.mailcheck.co) services:"
  status-website:
  favicon: https://www.mailcheck.co/favicon.png
  navbar:
    - title: Status
      href: /
    - title: Mailcheck
      href: https://www.mailcheck.co
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
commitMessages:
  commitAuthorName: "Status Bot"
  commitAuthorEmail: "status@mailcheck.co"
user-agent: MailCheck-co-status


# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
